apiVersion: v1
data:
  .dockerconfigjson: zabaseowany token -> w instrukcji jest jak stworzyc
kind: Secret
metadata:
  creationTimestamp: null
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
